language: node_js
node_js:
  - "stable"

addons:
  firefox: latest-unsigned

env:
  global:
    - DISPLAY=:99.0
    - JPM_FIREFOX_BINARY=./firefox/firefox

before_script:
  - sh -e /etc/init.d/xvfb start