# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.12.0'
  displayName: 'Install Node.js'
- script: npm --version
  displayName: 'npm version'
- script: npm install
  displayName: 'npm install'
- script: npm run build
  displayName: 'npm run build'
  